// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgG_hgezu13Yic43FZa6vmfObevcay7Y',
    appId: '1:833718891801:web:4144ca98dae49fb641c188',
    messagingSenderId: '833718891801',
    projectId: 'mycampus-project',
    authDomain: 'mycampus-project.firebaseapp.com',
    storageBucket: 'mycampus-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKc1DZZiJ8ZiH4vcXs4azYcU6pcpCrpo',
    appId: '1:833718891801:android:6388d13db4472de141c188',
    messagingSenderId: '833718891801',
    projectId: 'mycampus-project',
    storageBucket: 'mycampus-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAEkVoK1Hzpq-sCdfiRlu2-ulQyJP9Vs',
    appId: '1:833718891801:ios:d60def35b12f88aa41c188',
    messagingSenderId: '833718891801',
    projectId: 'mycampus-project',
    storageBucket: 'mycampus-project.firebasestorage.app',
    iosBundleId: 'com.example.myCampus',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAEkVoK1Hzpq-sCdfiRlu2-ulQyJP9Vs',
    appId: '1:833718891801:ios:d60def35b12f88aa41c188',
    messagingSenderId: '833718891801',
    projectId: 'mycampus-project',
    storageBucket: 'mycampus-project.firebasestorage.app',
    iosBundleId: 'com.example.myCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgG_hgezu13Yic43FZa6vmfObevcay7Y',
    appId: '1:833718891801:web:4764dc47fc89c2e241c188',
    messagingSenderId: '833718891801',
    projectId: 'mycampus-project',
    authDomain: 'mycampus-project.firebaseapp.com',
    storageBucket: 'mycampus-project.firebasestorage.app',
  );
}
